=== JanmanX/spiderframework/spiderframework/SpiderConf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Administrator (EMBRACE) -->
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Fox (ORiON) -->
<xs:schema xmlns:sp="http://fox.spider.configuration" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://fox.spider.configuration" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Spider">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Table" type="sp:TableSchema" maxOccurs="unbounded"/>
				<xs:element name="RelationProcessors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="sp:RelationProcessor" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PageTurners" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="sp:PageTurner" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="starter" type="xs:IDREF" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SpiderFlow" type="sp:SpiderFlow" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="sp:ItemAttributes"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DocumentParser" type="xs:anyType" abstract="true"/>
	<xs:element name="RowContentParser" type="xs:anyType" abstract="true"/>
	<xs:element name="RelationProcessor" type="xs:anyType" abstract="true"/>
	<xs:element name="PageTurner" type="xs:anyType" abstract="true"/>
	<xs:element name="RowFilter" type="xs:anyType" abstract="true"/>
	<xs:complexType name="SpiderFlow">
		<xs:sequence>
			<xs:element name="UrlPattern" type="xs:string"/>
			<xs:element name="DocumentParsers">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="sp:DocumentParser" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="RowContentParsers" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="sp:RowContentParser" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="RowFilters" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="sp:RowFilter" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="sp:ItemAttributes"/>
	</xs:complexType>
	<xs:element name="CellBasedDocumentParser" substitutionGroup="sp:DocumentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:DocumentParserItem">
					<xs:sequence>
						<xs:element name="RowContentParserId" type="xs:IDREF"/>
						<xs:element name="Path">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="RowFirstPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="RowNextPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="CellFirstPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="CellNextPath" type="xs:string" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="RepeaterDocumentParser" substitutionGroup="sp:DocumentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:DocumentParserItem">
					<xs:sequence>
						<xs:element name="RowContentParserId" type="xs:IDREF"/>
						<xs:element name="Path">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="FirstPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="NextPath" type="xs:string" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ForeignKeyRelationProcessor" type="sp:ForeignKeyRelationProcessor" substitutionGroup="sp:RelationProcessor"/>
	<xs:element name="TableDocumentParser" substitutionGroup="sp:DocumentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:DocumentParserItem">
					<xs:sequence>
						<xs:element name="RowContentParserId" type="xs:IDREF"/>
						<xs:element name="Path" type="xs:string"/>
						<xs:element name="StartRow" type="xs:int" minOccurs="0"/>
						<xs:element name="EndRow" type="xs:int" minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="AttributeRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string"/>
						<xs:element name="Attribute" type="xs:string"/>
						<xs:element name="ColumnName" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="XPathRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Trim" minOccurs="0"/>
						<xs:element name="Pair" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Path" type="xs:string"/>
									<xs:element name="ColumnName" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="RegexRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string"/>
						<xs:element name="Pair" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Regex" type="xs:string"/>
									<xs:element name="ColumnName" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="matchHTML" type="xs:boolean" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="PriorityXPathRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string" maxOccurs="unbounded"/>
						<xs:element name="ColumnName" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ConstantsRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Field" type="xs:string"/>
						<xs:element name="Type">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="URL"/>
									<xs:enumeration value="any"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="DefaultValue" type="xs:string" minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="RepeaterRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Path">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="FirstPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="NextPath" type="xs:string" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="ParsingInfo" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Column" type="xs:string"/>
									<xs:element name="MatcherPath" type="xs:string"/>
									<xs:element name="MatcherRegex" type="xs:string" minOccurs="0"/>
									<xs:element name="ValuePath" type="xs:string"/>
									<xs:element name="ValueRegex" type="xs:string" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="LinkedWebPageTurner" substitutionGroup="sp:PageTurner">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:PageTurnerItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="NamedWebPageTurner" substitutionGroup="sp:PageTurner">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:PageTurnerItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string"/>
						<xs:element name="Text" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="UrlWebPageTurner" substitutionGroup="sp:PageTurner">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:PageTurnerItem">
					<xs:sequence>
						<xs:element name="url" type="xs:string" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="DataTableWebPageTurner" substitutionGroup="sp:PageTurner">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:PageTurnerItem">
					<xs:sequence>
						<xs:element name="DataTable" type="xs:IDREF"/>
						<xs:element name="Field" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ForeignKeyRelationProcessor">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:sequence>
					<xs:element name="Parent">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Table" type="xs:IDREF"/>
								<xs:element name="Column" type="xs:string"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Child">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Table" type="xs:IDREF"/>
								<xs:element name="Column" type="xs:string"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ValueFilter" substitutionGroup="sp:RowFilter">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowFilterItem">
					<xs:sequence>
						<xs:element name="Constraint" maxOccurs="unbounded">
							<xs:complexType>
								<xs:choice>
									<xs:element name="NotNull"/>
									<xs:element name="Regexp" type="xs:string"/>
								</xs:choice>
								<xs:attribute name="FieldName" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="ItemAttributes">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:attributeGroup>
	<xs:complexType name="TableSchema">
		<xs:sequence>
			<xs:element name="Column" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="string"/>
								<xs:enumeration value="int"/>
								<xs:enumeration value="float"/>
								<xs:enumeration value="double"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="sp:ItemAttributes"/>
	</xs:complexType>
	<xs:complexType name="SpiderItem">
		<xs:attributeGroup ref="sp:ItemAttributes"/>
	</xs:complexType>
	<xs:complexType name="DocumentParserItem">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:attribute name="table" type="xs:IDREF" use="required"/>
				<xs:attribute name="relation" type="xs:IDREF" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RowFilterItem">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:attribute name="docparser" type="xs:IDREF" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RowContentParserItem">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:attribute name="isRoot" type="xs:boolean" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PageTurnerItem">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:sequence>
					<xs:element name="UrlPattern" type="xs:string" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute name="delay" type="xs:int" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== JanmanX/spiderframework/trunk/spiderframework/Configuration Files/pchome ebay.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<Spider xmlns="http://fox.spider.configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fox.spider.configuration
../SpiderConf.xsd" id="PCHome_eBay" name="">
	<Table id="UrlTable" name="">
		<Column type="string" name="url"/>
	</Table>
	<Table id="ItemTable" name="ItemTable">
		<Column type="string" name="Source"/>
		<Column type="string" name="Category"/>
		<Column type="string" name="Url"/>
		<Column type="string" name="ItemId"/>
		<Column type="string" name="Title"/>
		<Column type="string" name="ThumbnailUrl"/>	
		<Column type="string" name="Seller"/>
		<Column type="string" name="SellerGrade"/>
		<Column type="string" name="Price"/>
		<Column type="string" name="NumberOfItems"/>
		<Column type="string" name="StartingPrice"/>
		<Column type="string" name="SatisfiedPrice"/>
		<Column type="string" name="BidCount"/>
		<Column type="string" name="ItemStatus"/>
		<Column type="string" name="ItemLocation"/>
		<Column type="string" name="StartDate"/>
		<Column type="string" name="EndDate"/>
		<Column type="string" name="ShippingFee"/>
		<Column type="string" name="BidInfos"/>
	</Table>
	<PageTurners starter="CategoryPager">
		<LinkedWebPageTurner id="CategoryNextPage" name="" delay="400">
			<UrlPattern>http://class.ruten.com.tw/category/sub(_j\.php)?\?[0-9A-Za-z]+.*</UrlPattern>
			<Path>/BODY/DIV[1]/TABLE[0]/TBODY[0]/TR[1]/TD[0]/DIV[0]/{last-child}/A[0]</Path>
		</LinkedWebPageTurner>
		<UrlWebPageTurner id="CategoryPager" name="">
			<url>http://class.ruten.com.tw/category/sub\?0019000200020001</url>
			<url>http://class.ruten.com.tw/category/sub\?0019000200020004</url>
		</UrlWebPageTurner>
		<DataTableWebPageTurner id="DetailItemPager" name="" delay="1000">
			<DataTable>UrlTable</DataTable>
			<Field>url</Field>
		</DataTableWebPageTurner>
	</PageTurners>
	<SpiderFlow id="UrlParsingFlow" name="">
		<UrlPattern>http://class.ruten.com.tw/category/sub?[0-9A-Za-z]+.*</UrlPattern>
		<DocumentParsers>
			<TableDocumentParser id="UrlCollector" table="UrlTable" name="" >
				<RowContentParserId>UrlParser</RowContentParserId>
				<Path>/BODY/DIV[1]/TABLE[2]</Path>
				<StartRow>1</StartRow>
			</TableDocumentParser>
		</DocumentParsers>
		<RowContentParsers>
			<AttributeRowContentParser id="UrlParser" name="">
				<Path>TD[1]/STRONG[0]/A[0]</Path>
				<Attribute>HREF</Attribute>
				<ColumnName>url</ColumnName>
			</AttributeRowContentParser>
		</RowContentParsers>
		<RowFilters>
			<ValueFilter id="NullUrl" docparser="UrlCollector" name="">
				<Constraint FieldName="url">
					<NotNull/>
				</Constraint>
			</ValueFilter>
		</RowFilters>
	</SpiderFlow>
	<SpiderFlow id="DetailParsingFlow" name="">
		<UrlPattern>http://goods.ruten.com.tw/item/show\?[0-9A-Za-z]+</UrlPattern>
		<DocumentParsers>
			<RepeaterDocumentParser id="DummyRepeater" table="ItemTable" name="">
				<RowContentParserId>ItemValueParser</RowContentParserId>
				<Path>
					<FirstPath>/BODY/CENTER[0]</FirstPath>
					<NextPath>NULL[0]</NextPath>
				</Path>
			</RepeaterDocumentParser>
		</DocumentParsers>
		<RowContentParsers>
			<XPathRowContentParser id="ItemValueParser" name="">
				<Pair>
					<Path>TABLE[0]</Path>
					<ColumnName>Category</ColumnName>
				</Pair>
				<Pair>
					<Path>TABLE[1]/FORM[0]/TBODY[0]/TR[1]/TD[0]</Path>
					<ColumnName>Title</ColumnName>
				</Pair>
				<Pair>
					<Path>TABLE[1]/FORM[0]/TBODY[0]/TR[11]/TD[0]</Path>
					<ColumnName>BidInfos</ColumnName>
				</Pair>
				<Pair>
					<Path>TABLE[1]/FORM[0]/TBODY[0]/TR[7]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[1]/TABLE[0]/TBODY[0]/TR[7]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/A[0]</Path>
					<ColumnName>Seller</ColumnName>
				</Pair>
				<Pair>
					<Path>TABLE[1]/FORM[0]/TBODY[0]/TR[7]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[1]/TABLE[0]/TBODY[0]/TR[7]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/A[1]</Path>
					<ColumnName>SellerGrade</ColumnName>
				</Pair>
			</XPathRowContentParser>
			<RegexRowContentParser id="RegexParser" name="">
				<Path>TABLE[1]/FORM[0]/TBODY[0]/TR[1]/TD[1]</Path>
				<Pair>
					<Regex>([0-9a-zA-Z]+)</Regex>
					<ColumnName>ItemId</ColumnName>
				</Pair>
			</RegexRowContentParser>
			<RegexRowContentParser id="ItemStatusParser" name="">
				<Path>TABLE[1]/FORM[0]/TBODY[0]/TR[7]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[1]/TABLE[0]/TBODY[0]/TR[5]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]</Path>
				<Pair>
					<Regex>物品狀況：([^\r\n]+)</Regex>
					<ColumnName>ItemStatus</ColumnName>
				</Pair>
			</RegexRowContentParser>
			<AttributeRowContentParser id="ThumbnailParser" name="">
				<Path>TABLE[1]/FORM[0]/TBODY[0]/TR[7]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/DIV[0]/A[0]/IMG[0]</Path>
				<Attribute>SRC</Attribute>
				<ColumnName>ThumbnailUrl</ColumnName>
			</AttributeRowContentParser>
			<ConstantsRowContentParser id="DetailItemUrlParser" name="">
				<Field>Url</Field>
				<Type>URL</Type>
			</ConstantsRowContentParser>
			<ConstantsRowContentParser id="SourceParser" name="">
				<Field>Source</Field>
				<Type>any</Type>
				<DefaultValue>Pchome &amp; eBay</DefaultValue>
			</ConstantsRowContentParser>
			<RepeaterRowContentParser id="PriceParser" name="">
				<Path>
					<FirstPath>TABLE[1]/FORM[0]/TBODY[0]/TR[7]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[1]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[0]</FirstPath>
					<NextPath>{following-sibling:TR}</NextPath>
				</Path>
				<ParsingInfo>
					<Column>StartingPrice</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>開始價格</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>Price</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>開始價格</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>Price</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>目前出價</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>SatisfiedPrice</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>直接購買價</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
			</RepeaterRowContentParser>
			<RepeaterRowContentParser id="DetailItemParser2" name="">
				<Path>
					<FirstPath>TABLE[1]/FORM[0]/TBODY[0]/TR[7]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[1]/TABLE[0]/TBODY[0]/TR[3]/TD[0]/TABLE[0]/TBODY[0]/TR[0]</FirstPath>
					<NextPath>{following-sibling:TR}</NextPath>
				</Path>
				<ParsingInfo>
					<Column>StartDate</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>\s</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}) ~</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>EndDate</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>\s</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex> ~ ([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2})</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>NumberOfItems</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>商品數量</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>BidCount</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>出價次數</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>ShippingFee</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>運費</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
				</ParsingInfo>
				<ParsingInfo>
					<Column>ItemLocation</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>物品所在地</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
				</ParsingInfo>
			</RepeaterRowContentParser>
			
		</RowContentParsers>
	</SpiderFlow>
</Spider>

=== JanmanX/spiderframework/trunk/spiderframework/SpiderRuntime/TestCase1_NBA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<Spider xmlns="http://fox.spider.configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fox.spider.configuration
K:\work\2005\Spider\SpiderConf.xsd" id="NBA_1" name="NBA Spider for 2006-12-05 ~">
	<Table id="GameScore" name="Game Scoreboard">
		<Column type="string" name="Team"/>
		<Column type="int" name="Section1"/>
		<Column type="int" name="Section2"/>
		<Column type="int" name="Section3"/>
		<Column type="int" name="Section4"/>
		<Column type="int" name="Total"/>
	</Table>
	<PageTurners starter="uTurner">
		<UrlWebPageTurner id="uTurner" name="Url">
			<url>http://www.nba.com/games/20070406/DALDEN/boxscore.html</url>
			<url>http://www.nba.com/games/20070406/TORPHI/boxscore.html</url>
			<url>http://www.nba.com/games/20070406/INDCHA/boxscore.html</url>
			<url>http://www.nba.com/games/20070406/MIABOS/boxscore.html</url>
			<url>http://www.nba.com/games/20070406/CLEWAS/boxscore.html</url>
			<url>http://www.nba.com/games/20070406/MINNYK/boxscore.html</url>
		</UrlWebPageTurner>
	</PageTurners>
	<SpiderFlow id="GameScoreFlow" name="Parse Game Score">
		<UrlPattern>http://www.nba.com/games/[0-9]{8}/[A-Z]{6}/boxscore.html</UrlPattern>
		<DocumentParsers>
			<TableDocumentParser id="tParser" table="GameScore" name="GameScore Table Parser">
				<RowContentParserId>xpath</RowContentParserId>
				<Path>/BODY/TABLE[0]/TBODY[0]/TR[0]/TD[0]/DIV[0]/DIV[1]/DIV[0]/DIV[0]/DIV[1]/TABLE[0]</Path>
				<StartRow>1</StartRow>
				<EndRow>3</EndRow>
			</TableDocumentParser>
		</DocumentParsers>
		<RowContentParsers>
			<XPathRowContentParser id="xpath" name="A Parser">
				<Pair>
					<Path>TH[0]</Path>
					<ColumnName>Team</ColumnName>
				</Pair>
				<Pair>
					<Path>TD[0]</Path>
					<ColumnName>Section1</ColumnName>
				</Pair>
				<Pair>
					<Path>TD[1]</Path>
					<ColumnName>Section2</ColumnName>
				</Pair>
				<Pair>
					<Path>TD[2]</Path>
					<ColumnName>Section3</ColumnName>
				</Pair>
				<Pair>
					<Path>TD[3]</Path>
					<ColumnName>Section4</ColumnName>
				</Pair>
				<Pair>
					<Path>TD[8]</Path>
					<ColumnName>Total</ColumnName>
				</Pair>
			</XPathRowContentParser>
		</RowContentParsers>
		<PageTurner>uTurner</PageTurner>
	</SpiderFlow>
</Spider>
