=== JanmanX/spiderframework/spiderframework/SpiderConf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Administrator (EMBRACE) -->
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Fox (ORiON) -->
<xs:schema xmlns:sp="http://fox.spider.configuration" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://fox.spider.configuration" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Spider">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Table" type="sp:TableSchema" maxOccurs="unbounded"/>
				<xs:element name="RelationProcessors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="sp:RelationProcessor" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PageTurners" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="sp:PageTurner" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="starter" type="xs:IDREF" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SpiderFlow" type="sp:SpiderFlow" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="sp:ItemAttributes"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DocumentParser" type="xs:anyType" abstract="true"/>
	<xs:element name="RowContentParser" type="xs:anyType" abstract="true"/>
	<xs:element name="RelationProcessor" type="xs:anyType" abstract="true"/>
	<xs:element name="PageTurner" type="xs:anyType" abstract="true"/>
	<xs:element name="RowFilter" type="xs:anyType" abstract="true"/>
	<xs:complexType name="SpiderFlow">
		<xs:sequence>
			<xs:element name="UrlPattern" type="xs:string"/>
			<xs:element name="DocumentParsers">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="sp:DocumentParser" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="RowContentParsers" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="sp:RowContentParser" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="RowFilters" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="sp:RowFilter" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="sp:ItemAttributes"/>
	</xs:complexType>
	<xs:element name="CellBasedDocumentParser" substitutionGroup="sp:DocumentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:DocumentParserItem">
					<xs:sequence>
						<xs:element name="RowContentParserId" type="xs:IDREF"/>
						<xs:element name="Path">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="RowFirstPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="RowNextPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="CellFirstPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="CellNextPath" type="xs:string" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="RepeaterDocumentParser" substitutionGroup="sp:DocumentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:DocumentParserItem">
					<xs:sequence>
						<xs:element name="RowContentParserId" type="xs:IDREF"/>
						<xs:element name="Path">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="FirstPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="NextPath" type="xs:string" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ForeignKeyRelationProcessor" type="sp:ForeignKeyRelationProcessor" substitutionGroup="sp:RelationProcessor"/>
	<xs:element name="TableDocumentParser" substitutionGroup="sp:DocumentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:DocumentParserItem">
					<xs:sequence>
						<xs:element name="RowContentParserId" type="xs:IDREF"/>
						<xs:element name="Path" type="xs:string"/>
						<xs:element name="StartRow" type="xs:int" minOccurs="0"/>
						<xs:element name="EndRow" type="xs:int" minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="AttributeRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string"/>
						<xs:element name="Attribute" type="xs:string"/>
						<xs:element name="ColumnName" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="XPathRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Trim" minOccurs="0"/>
						<xs:element name="Pair" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Path" type="xs:string"/>
									<xs:element name="ColumnName" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="RegexRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string"/>
						<xs:element name="Pair" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Regex" type="xs:string"/>
									<xs:element name="ColumnName" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="matchHTML" type="xs:boolean" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="PriorityXPathRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string" maxOccurs="unbounded"/>
						<xs:element name="ColumnName" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ConstantsRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Field" type="xs:string"/>
						<xs:element name="Type">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="URL"/>
									<xs:enumeration value="any"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="DefaultValue" type="xs:string" minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="RepeaterRowContentParser" substitutionGroup="sp:RowContentParser">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowContentParserItem">
					<xs:sequence>
						<xs:element name="Path">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="FirstPath" type="xs:string" maxOccurs="unbounded"/>
									<xs:element name="NextPath" type="xs:string" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="ParsingInfo" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Column" type="xs:string"/>
									<xs:element name="MatcherPath" type="xs:string"/>
									<xs:element name="MatcherRegex" type="xs:string" minOccurs="0"/>
									<xs:element name="ValuePath" type="xs:string"/>
									<xs:element name="ValueRegex" type="xs:string" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="LinkedWebPageTurner" substitutionGroup="sp:PageTurner">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:PageTurnerItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="NamedWebPageTurner" substitutionGroup="sp:PageTurner">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:PageTurnerItem">
					<xs:sequence>
						<xs:element name="Path" type="xs:string"/>
						<xs:element name="Text" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="UrlWebPageTurner" substitutionGroup="sp:PageTurner">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:PageTurnerItem">
					<xs:sequence>
						<xs:element name="url" type="xs:string" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="DataTableWebPageTurner" substitutionGroup="sp:PageTurner">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:PageTurnerItem">
					<xs:sequence>
						<xs:element name="DataTable" type="xs:IDREF"/>
						<xs:element name="Field" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ForeignKeyRelationProcessor">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:sequence>
					<xs:element name="Parent">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Table" type="xs:IDREF"/>
								<xs:element name="Column" type="xs:string"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Child">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Table" type="xs:IDREF"/>
								<xs:element name="Column" type="xs:string"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ValueFilter" substitutionGroup="sp:RowFilter">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="sp:RowFilterItem">
					<xs:sequence>
						<xs:element name="Constraint" maxOccurs="unbounded">
							<xs:complexType>
								<xs:choice>
									<xs:element name="NotNull"/>
									<xs:element name="Regexp" type="xs:string"/>
								</xs:choice>
								<xs:attribute name="FieldName" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="ItemAttributes">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:attributeGroup>
	<xs:complexType name="TableSchema">
		<xs:sequence>
			<xs:element name="Column" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="string"/>
								<xs:enumeration value="int"/>
								<xs:enumeration value="float"/>
								<xs:enumeration value="double"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="sp:ItemAttributes"/>
	</xs:complexType>
	<xs:complexType name="SpiderItem">
		<xs:attributeGroup ref="sp:ItemAttributes"/>
	</xs:complexType>
	<xs:complexType name="DocumentParserItem">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:attribute name="table" type="xs:IDREF" use="required"/>
				<xs:attribute name="relation" type="xs:IDREF" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RowFilterItem">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:attribute name="docparser" type="xs:IDREF" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RowContentParserItem">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:attribute name="isRoot" type="xs:boolean" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PageTurnerItem">
		<xs:complexContent>
			<xs:extension base="sp:SpiderItem">
				<xs:sequence>
					<xs:element name="UrlPattern" type="xs:string" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute name="delay" type="xs:int" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== JanmanX/spiderframework/trunk/spiderframework/Configuration Files/Yahoo_bid.xml
<?xml version="1.0" encoding="UTF-8"?>
<Spider xmlns="http://fox.spider.configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fox.spider.configuration
..\SpiderConf.xsd" id="Yahoo_bid" name="Yahoo Bid">
	<Table id="ItemList" name="ItemList">
		<Column type="string" name="url"/>
	</Table>
	<Table id="ItemTable" name="ItemTable">
		<Column type="string" name="Source"/>
		<Column type="string" name="Category"/>
		<Column type="string" name="Url"/>
		<Column type="string" name="ItemId"/>
		<Column type="string" name="Title"/>
		<Column type="string" name="ThumbnailUrl"/>	
		<Column type="string" name="Seller"/>
		<Column type="string" name="SellerGrade"/>
		<Column type="string" name="Price"/>
		<Column type="string" name="NumberOfItems"/>
		<Column type="string" name="StartingPrice"/>
		<Column type="string" name="SatisfiedPrice"/>
		<Column type="string" name="BidCount"/>
		<Column type="string" name="ItemStatus"/>
		<Column type="string" name="ItemLocation"/>
		<Column type="string" name="StartDate"/>
		<Column type="string" name="EndDate"/>
		<Column type="string" name="ShippingFee"/>
		<Column type="string" name="BidInfos"/>
	</Table>
	<PageTurners starter="Starter">
		<LinkedWebPageTurner id="BidListPager" name="" delay="50">
			<UrlPattern>http://tw.bid.yahoo.com/tw/[0-9]+-category-leaf.html\?.r=[0-9]+.*</UrlPattern>
			<Path>/BODY/DIV[0]/DIV[0]/DIV[4]/DIV[1]/DIV[0]/DIV[1]/DIV[5]/P/SPAN/A</Path>
		</LinkedWebPageTurner>
		<UrlWebPageTurner id="Starter" name="">
			<url>http://tw.bid.yahoo.com/tw/2092081437-category-leaf.html?.r=1181903300</url>
			<url>http://tw.bid.yahoo.com/tw/2092081438-category-leaf.html?.r=1181903300</url>
			<url>http://tw.bid.yahoo.com/tw/2092081439-category-leaf.html?.r=1181903300</url>
		</UrlWebPageTurner>
		<DataTableWebPageTurner id="DetailPager" name="" delay="500">
			<DataTable>ItemList</DataTable>
			<Field>url</Field>
		</DataTableWebPageTurner>
	</PageTurners>
	<SpiderFlow id="BidListUrlParser" name="BidListUrlParser">
		<UrlPattern>http://tw.bid.yahoo.com/tw/[0-9]+-category-leaf.html\?.r=[0-9]+.*</UrlPattern>
		<DocumentParsers>
			<TableDocumentParser id="BidListTableParser" table="ItemList" name="BidListTableParser">
				<RowContentParserId>BidUrlParser</RowContentParserId>
				<Path>/BODY/DIV[0]/DIV[0]/DIV[4]/DIV[1]/DIV[0]/DIV[1]/TABLE[1]</Path>
			</TableDocumentParser>
		</DocumentParsers>
		<RowContentParsers>
			<AttributeRowContentParser id="BidUrlParser" name="BidUrlParser">
				<Path>TH[0]/A[0]</Path>
				<Attribute>HREF</Attribute>
				<ColumnName>url</ColumnName>
			</AttributeRowContentParser>
		</RowContentParsers>
	</SpiderFlow>
	<SpiderFlow id="BidDetailParser" name="">
		<UrlPattern>http://tw\.([a-z][0-9]\.)?page\.bid\.yahoo\.com/tw/auction/.+</UrlPattern>
		<DocumentParsers>
			<RepeaterDocumentParser id="DataParser" table="ItemTable" name="">
				<RowContentParserId>PathParser</RowContentParserId>
				<Path>
					<FirstPath>/BODY/DIV[0]</FirstPath>
					<NextPath>NULL[0]</NextPath>
				</Path>
			</RepeaterDocumentParser>
		</DocumentParsers>
		<RowContentParsers>
			<RepeaterRowContentParser id="PathParser" name="">
				<Path>
					<FirstPath>TABLE[3]/TBODY[0]/TR[0]/TD[1]/TABLE[0]/TBODY[0]/TR[1]</FirstPath>
					<NextPath>{following-sibling:TR}</NextPath>
				</Path>
				<ParsingInfo>
					<Column>Price</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>目前出價</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>NumberOfItems</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>商品數量</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>BidCount</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>出價次數</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>StartingPrice</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>起標價格</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>ItemStatus</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>商品新舊</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
				</ParsingInfo>
				<ParsingInfo>
					<Column>ItemLocation</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>所在地區</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
				</ParsingInfo>
				<ParsingInfo>
					<Column>SatisfiedPrice</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>直接購買價</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
					<ValueRegex>([0-9,]+)</ValueRegex>
				</ParsingInfo>
				<ParsingInfo>
					<Column>ShippingFee</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>運送費用</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
				</ParsingInfo>
				<ParsingInfo>
					<Column>StartDate</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>開始時間</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
				</ParsingInfo>
				<ParsingInfo>
					<Column>EndDate</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>結束時間</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
				</ParsingInfo>
				<ParsingInfo>
					<Column>ItemId</Column>
					<MatcherPath>TD[0]</MatcherPath>
					<MatcherRegex>拍賣編號</MatcherRegex>
					<ValuePath>{following-sibling:TD}</ValuePath>
				</ParsingInfo>
			</RepeaterRowContentParser>
			<ConstantsRowContentParser id="ItemUrlParser" name="">
				<Field>Url</Field>
				<Type>URL</Type>
			</ConstantsRowContentParser>
			<ConstantsRowContentParser id="SourceParser" name="">
				<Field>Source</Field>
				<Type>any</Type>
				<DefaultValue>Yahoo</DefaultValue>
			</ConstantsRowContentParser>
			<XPathRowContentParser id="OtherInfoParser" name="">
				<Pair>
					<Path>TABLE[3]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[1]/TD[0]/A[0]</Path>
					<ColumnName>Seller</ColumnName>
				</Pair>
				<Pair>
					<Path>TABLE[3]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[1]/TD[0]/B[0]/A[0]</Path>
					<ColumnName>SellerGrade</ColumnName>
				</Pair>
				<Pair>
					<Path>TABLE[1]</Path>
					<ColumnName>Category</ColumnName>
				</Pair>
				<Pair>
					<Path>TABLE[5]</Path>
					<ColumnName>BidInfos</ColumnName>
				</Pair>
			</XPathRowContentParser>
			<AttributeRowContentParser id="ThumbnailParser" name="">
				<Path>TABLE[2]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/IMG[0]</Path>
				<Attribute>HREF</Attribute>
				<ColumnName>ThumbnailUrl</ColumnName>
			</AttributeRowContentParser>
			<PriorityXPathRowContentParser id="TitleParser" name="">
				<Path>TABLE[2]/TBODY[0]/TR[0]/TD[1]/TABLE[0]</Path>
				<Path>TABLE[2]/TBODY[0]/TR[0]/TD[0]/TABLE[0]</Path>
				<ColumnName>Title</ColumnName>
			</PriorityXPathRowContentParser>
		</RowContentParsers>
	</SpiderFlow>
</Spider>

=== JanmanX/spiderframework/trunk/spiderframework/Configuration Files/PCHome.xml
<?xml version="1.0" encoding="UTF-8"?>
<Spider xmlns="http://fox.spider.configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fox.spider.configuration
..\SpiderConf.xsd" id="PCHome" name="PCHome Runtime">
	<Table id="UrlTable" name="UrlTable">
		<Column type="string" name="url"/>
	</Table>
	<Table id="DataItem" name="">
		<Column type="string" name="url"/>
		<Column type="string" name="data1"/>
		<Column type="string" name="data2"/>
	</Table>
	<PageTurners starter="Starter">
		<LinkedWebPageTurner id="URLType2PageTurner" name="">
			<UrlPattern>http://shopping.pchome.com.tw/\?mod=store&amp;func=style_show&amp;SR_NO=[A-Z0-9]+(&amp;.+)?</UrlPattern>
			<Path>/BODY/DIV[0]/DIV[0]/TABLE[2]/TBODY[0]/TR[1]/TD[0]/TABLE[2]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[1]/TD[0]/TABLE[0]/TBODY[0]/TR[1]/TD[2]/SPAN[2]/SPAN[0]/A[0]</Path>
		</LinkedWebPageTurner>
		<DataTableWebPageTurner id="DataTableItem" name="">
			<UrlPattern>(http://shopping.pchome.com.tw/\?mod=store&amp;func=style_show&amp;SR_NO=[A-Z0-9]+(&amp;.+)?|http://shopping.pchome.com.tw/\?mod=item&amp;func=exhibit&amp;IT_NO=[A-Z\-0-9]+&amp;SR_NO=[A-Z0-9]+&amp;ROWNO=[0-9]+)</UrlPattern>
			<DataTable>UrlTable</DataTable>
			<Field>url</Field>
		</DataTableWebPageTurner>
		<UrlWebPageTurner id="Starter" name="">
			<url>http://shopping.pchome.com.tw/?mod=store&amp;func=style_show&amp;SR_NO=ABAL1S</url>
			<url>http://shopping.pchome.com.tw/?mod=store&amp;func=style_show&amp;SR_NO=AEAA3A</url>
		</UrlWebPageTurner>
	</PageTurners>
	<SpiderFlow id="UrlParsingFlowType1" name="Parse Url Flow">
		<UrlPattern>http://shopping.pchome.com.tw/\?mod=store&amp;func=style_show&amp;SR_NO=[A-Z0-9]+</UrlPattern>
		<DocumentParsers>
			<RepeaterDocumentParser id="Type1Repeater" table="UrlTable" name="">
				<RowContentParserId>UrlAttributeParser</RowContentParserId>
				<Path>
					<FirstPath>/BODY/DIV[0]/DIV[0]/TABLE[2]/TBODY[0]/TR[1]/TD[0]/TABLE[1]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[1]/TD[0]/A[0]</FirstPath>
					<FirstPath>/BODY/DIV[0]/DIV[0]/TABLE[2]/TBODY[0]/TR[1]/TD[0]/TABLE[1]/TBODY[0]/TR[0]/TD[2]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[1]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/A[0]</FirstPath>
					<FirstPath>/BODY/DIV[0]/DIV[0]/TABLE[2]/TBODY[0]/TR[1]/TD[0]/TABLE[1]/TBODY[0]/TR[0]/TD[2]/TABLE[0]/TBODY[0]/TR[2]/TD[0]/TABLE[0]/TBODY[0]/TR[1]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/A[0]</FirstPath>
					<NextPath>../../../../../{following-sibling}/{following-sibling}/TABLE[0]/TBODY[0]/TR[1]/TD[0]/A[0]</NextPath>
					<NextPath>../../../../../../../../../{following-sibling}/{following-sibling}/TABLE[0]/TBODY[0]/TR[1]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/A[0]</NextPath>
					<NextPath>../../../../../../../../../{following-sibling}/{following-sibling}/TABLE[0]/TBODY[0]/TR[1]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/A[0]</NextPath>
				</Path>
			</RepeaterDocumentParser>
		</DocumentParsers>
		<RowContentParsers>
			<AttributeRowContentParser id="UrlAttributeParser" name="UrlAttributeParser" isRoot="true">
				<Path>.</Path>
				<Attribute>HREF</Attribute>
				<ColumnName>url</ColumnName>
			</AttributeRowContentParser>
		</RowContentParsers>
	</SpiderFlow>
	<SpiderFlow id="UrlParsingFlowType2" name="Parse Url Flow">
		<UrlPattern>http://shopping.pchome.com.tw/\?mod=store&amp;func=style_show&amp;SR_NO=[A-Z0-9]+(&amp;.+)?</UrlPattern>
		<DocumentParsers>
			<RepeaterDocumentParser id="Type2Repeater" table="UrlTable" name="">
				<RowContentParserId>Type2UrlAttributeParser1</RowContentParserId>
				<Path>
					<FirstPath>/BODY/DIV[0]/DIV[0]/TABLE[2]/TBODY[0]/TR[1]/TD[0]/TABLE[2]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[1]/TD[0]/TABLE[1]/TBODY[0]/TR[0]/TD[0]</FirstPath>
					<NextPath>{following-sibling}/{following-sibling}/{following-sibling}</NextPath>
					<NextPath>../../../{following-sibling}/{following-sibling}/TBODY[0]/TR[0]/TD[0]</NextPath>
				</Path>
			</RepeaterDocumentParser>
		</DocumentParsers>
		<RowContentParsers>
			<AttributeRowContentParser id="Type2UrlAttributeParser1" name="UrlAttributeParser2" isRoot="true">
				<Path>TABLE[0]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[2]/TD[0]/A[0]</Path>
				<Attribute>HREF</Attribute>
				<ColumnName>url</ColumnName>
			</AttributeRowContentParser>
		</RowContentParsers>
		<RowFilters>
			<ValueFilter id="Type1UrlFilter" docparser="Type1Repeater" name="">
				<Constraint FieldName="url">
					<NotNull/>
				</Constraint>
			</ValueFilter>
			<ValueFilter id="Type2UrlFilter" docparser="Type2Repeater" name="">
				<Constraint FieldName="url">
					<NotNull/>
				</Constraint>
			</ValueFilter>
		</RowFilters>
	</SpiderFlow>
	<SpiderFlow id="DataItemFlow" name="">
		<UrlPattern>http://shopping.pchome.com.tw/\?mod=item&amp;func=exhibit&amp;IT_NO=[A-Z\-0-9]+&amp;SR_NO=[A-Z0-9]+&amp;ROWNO=[0-9]+</UrlPattern>
		<DocumentParsers>
			<RepeaterDocumentParser id="DataItemParser" table="DataItem" name="">
				<RowContentParserId>DataItemRowParser</RowContentParserId>
				<Path>
					<FirstPath>/BODY/DIV[0]/DIV[0]/TABLE[2]/TBODY[0]/TR[1]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[0]/FORM[0]</FirstPath>
					<NextPath>../NULL[0]</NextPath>
				</Path>
			</RepeaterDocumentParser>
		</DocumentParsers>
		<RowContentParsers>
			<XPathRowContentParser id="DataItemRowParser" name="" isRoot="true">
				<Pair>
					<Path>TABLE[0]/TBODY[0]/TR[1]/TD[0]/TABLE[0]/TBODY[0]/TR[0]/TD[1]/FONT[0]</Path>
					<ColumnName>data1</ColumnName>
				</Pair>
				<Pair>
					<Path>TABLE[1]/TBODY[0]/TR[1]/TD[1]/TABLE[1]/TBODY[0]/TR[0]/TD[1]/FONT[1]</Path>
					<ColumnName>data2</ColumnName>
				</Pair>
			</XPathRowContentParser>
			<ConstantsRowContentParser id="UrlFiller" name="">
				<Field>url</Field>
				<Type>URL</Type>
			</ConstantsRowContentParser>
		</RowContentParsers>
	</SpiderFlow>
</Spider>
